### ISSUE TITLE
Error from PDBFixer

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/cosolvkit#16]
I am trying to run `create_cosolvent_system` from CosolvKit which I installed in a fresh environment from conda-forge

```
(cosolvkit) [ahansel@nodea0110]$ create_cosolvent_system -c config.json 

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

Traceback (most recent call last):
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/bin/create_cosolvent_system", line 6, in <module>
    from cosolvkit.cli.create_cosolvent_system import main
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/__init__.py", line 7, in <module>
    from .cosolvent_system import CosolventSystem, CosolventMolecule
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/cosolvent_system.py", line 22, in <module>
    from cosolvkit.utils import fix_pdb, MutuallyExclusiveParametersError
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/utils.py", line 23, in <module>
    import pdbfixer
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/lib/python3.11/site-packages/pdbfixer/__init__.py", line 2, in <module>
    from .pdbfixer import PDBFixer
  File "/gpfs/home/ahansel/micromamba/envs/cosolvkit/lib/python3.11/site-packages/pdbfixer/pdbfixer.py", line 38, in <module>
    from simtk.openmm.app.internal.pdbstructure import PdbStructure
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'
```

**Comment by nbruciaferri** [comment]
Never reproduced.

Closing this issue
