### ISSUE TITLE
KeyError: 'position'

### ISSUE THREAD

**Issue by allisonbarkdull** [forlilab/cosolvkit#30]
Traceback (most recent call last):
  File "/gpfs/home/abarkdull/micromamba/envs/cosolvkit/bin/create_cosolvent_system", line 33, in <module>
    sys.exit(load_entry_point('cosolvkit', 'console_scripts', 'create_cosolvent_system')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/abarkdull/software/cosolvkit/cosolvkit/cli/create_cosolvent_system.py", line 139, in main
    cosolv_system.save_topology(topology=cosolv_system.modeller.topology, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/abarkdull/software/cosolvkit/cosolvkit/cosolvent_system.py", line 407, in save_topology
    pos_extension
 = MD_FORMAT_EXTENSIONS[simulation_format]['position']
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'position'


[forcefields.json](https://github.com/user-attachments/files/17282988/forcefields.json)
[config.json](https://github.com/user-attachments/files/17282989/config.json)
[cosolvents.json](https://github.com/user-attachments/files/17282990/cosolvents.json)

**Comment by allisonbarkdull** [comment]
fixed in https://github.com/forlilab/cosolvkit/pull/31
