### ISSUE TITLE
Missing essential files under results/ when trying the example code.

### ISSUE THREAD

**Issue by archaeaMby** [forlilab/cosolvkit#32]
When running "create_cosolvent_system -c cosolvkit/data/config.json", encountering error about cannot find a pdb file under results/, like the pasted code. In the config.json, the md_format used as "openmm". Similar error shows when changing the md_format into "gromacs".
`Running MD simulation
Starting MD simulation from the files: results/system.pdb, results/system.xml
Traceback (most recent call last):
  File "/gpfs/home/bma/miniconda3/envs/cosolvkit/bin/create_cosolvent_system", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/gpfs/home/bma/miniconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/cli/create_cosolvent_system.py", line 163, in main
    run_simulation(
  File "/gpfs/home/bma/miniconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/simulation.py", line 74, in run_simulation
    pdb = app.PDBFile(f'{results_path}/system.pdb')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/bma/miniconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/pdbfile.py", line 93, in __init__
    inputfile = open(file)
                ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/system.pdb'`

**Comment by nbruciaferri** [comment]
I believe your error is because of the config file.

If you look at it you'll notice that from some reason the `run_cosolvent_system` parameter is set to `false` and the `run_md` is set to `true`. That means that `cosolvkit` expects a `system.pdb` file to be already present in the results folder (that is usually created by the `run_cosolvent_system`. I pushed a modified version of the `config.json` with the flags set to the right defaults, please give it another try and see if that fixes the error.

**Comment by archaeaMby** [comment]
It works now :D

**Comment by Gsk468** [comment]
Hi, I am also similar errors for gromacs, amber and charmm:

For Gromacs:

Protein present
Building cosolvent system
Parametrizing system with forcefields
Box Volume: 447.2763332314724 nm**3
	447276.3332314724 A^3
Volume protein: 24610.0 A^3
Volume requested for cosolvents: 47.05 nm**3
Volume available for cosolvents: 211.333 nm**3
Attempting to place 382 copies of benzene
Done!
Attempting to place 25 copies of methanol
Done!
Attempting to place 50 copies of propane
Done!
Attempting to place 30 copies of imidazole
Done!
Attempting to place 10 copies of acetamide
Done!
Added cosolvents:
benzene: 382
methanol: 25
propane: 50
imidazole: 30
acetamide: 10
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
Waters added: 6776
Creating system
Saving topology file
Running MD simulation
Starting MD simulation from the files: results/system.prmtop, results/system.rst7
Traceback (most recent call last):
  File "/home/gsk/anaconda3/envs/cosolvkit/bin/create_cosolvent_system", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/cli/create_cosolvent_system.py", line 163, in main
    run_simulation(
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/simulation.py", line 61, in run_simulation
    positions = app.GromacsGroFile(positions)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/gromacsgrofile.py", line 134, in __init__
    with open(file) as grofile:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/system.rst7'



For Charmm:

Protein present
Building cosolvent system
Parametrizing system with forcefields
Box Volume: 445.6690460022139 nm**3
	445669.0460022139 A^3
Volume protein: 24640.0 A^3
Volume requested for cosolvents: 46.85 nm**3
Volume available for cosolvents: 210.515 nm**3
Attempting to place 380 copies of benzene
Done!
Attempting to place 25 copies of methanol
Done!
Attempting to place 50 copies of propane
Done!
Attempting to place 30 copies of imidazole
Done!
Attempting to place 10 copies of acetamide
Done!
Added cosolvents:
benzene: 380
methanol: 25
propane: 50
imidazole: 30
acetamide: 10
Waters added: 11564
Creating system
Saving topology file
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/parmed/openmm/topsystem.py:451: OpenMMWarning: Detected incomplete exceptions. Not supported.
  warnings.warn('Detected incomplete exceptions. Not supported.', OpenMMWarning)
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/parmed/openmm/topsystem.py:203: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn(f'Unsupported Force type {force.__class__.__name__}', OpenMMWarning)
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/parmed/openmm/topsystem.py:203: OpenMMWarning: Unsupported Force type CustomBondForce
  warnings.warn(f'Unsupported Force type {force.__class__.__name__}', OpenMMWarning)
Running MD simulation
Starting MD simulation from the files: results/system.prmtop, results/system.rst7
Traceback (most recent call last):
  File "/home/gsk/anaconda3/envs/cosolvkit/bin/create_cosolvent_system", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/cli/create_cosolvent_system.py", line 163, in main
    run_simulation(
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/simulation.py", line 64, in run_simulation
    topology = app.CharmmPsfFile(topology)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/charmmpsffile.py", line 73, in newfunc
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/charmmpsffile.py", line 192, in __init__
    raise IOError('Could not find PSF file %s' % psf_name)
OSError: Could not find PSF file results/system.prmtop


For Amber:

Protein present
Building cosolvent system
Parametrizing system with forcefields
Box Volume: 436.71501034724275 nm**3
	436715.01034724276 A^3
Volume protein: 24620.0 A^3
Volume requested for cosolvents: 46.05 nm**3
Volume available for cosolvents: 206.048 nm**3
Attempting to place 372 copies of benzene
Done!
Attempting to place 25 copies of methanol
Done!
Attempting to place 50 copies of propane
Done!
Attempting to place 30 copies of imidazole
Done!
Attempting to place 10 copies of acetamide
Done!
Added cosolvents:
benzene: 372
methanol: 25
propane: 50
imidazole: 30
acetamide: 10
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
Waters added: 6533
Creating system
Saving topology file
Running MD simulation
Starting MD simulation from the files: results/system.prmtop, results/system.rst7
Selecting simulation platform
Using GPU:CUDA
Adding reporters to the simulation
Setting positions for the simulation
Minimizing system's energy
Heating system in NVT ensemble for 0.1 ns
Temperature set to 5 K.
Temperature set to 10 K.
Temperature set to 15 K.
Temperature set to 20 K.
Temperature set to 25 K.
Temperature set to 30 K.
Temperature set to 35 K.
Temperature set to 40 K.
Temperature set to 45 K.
Temperature set to 50 K.
Temperature set to 55 K.
Temperature set to 60 K.
Temperature set to 65 K.
Temperature set to 70 K.
Temperature set to 75 K.
#"Progress (%)"	"Step"	"Time (ps)"	"Potential Energy (kJ/mole)"	"Kinetic Energy (kJ/mole)"	"Total Energy (kJ/mole)"	"Temperature (K)"	"Box Volume (nm^3)"	"Density (g/mL)"	"Speed (ns/day)"	"Time Remaining"
0.4%	25000	25.00000000000757	-332807.7966208563	20671.88508291353	-312135.91153794277	73.93191299457635	436.71501073010984	0.6650702953374323	0	--
Temperature set to 80 K.
Temperature set to 85 K.
Temperature set to 90 K.
Temperature set to 95 K.
Temperature set to 100 K.
Temperature set to 105 K.
Temperature set to 110 K.
Temperature set to 115 K.
Temperature set to 120 K.
Temperature set to 125 K.
Temperature set to 130 K.
Temperature set to 135 K.
Temperature set to 140 K.
Temperature set to 145 K.
Temperature set to 150 K.
0.8%	50000	49.99999999997417	-317114.3394192399	41369.3151043344	-275745.0243149055	147.9551861221837	436.71501073010984	0.6650702953374323	396	22:53
Temperature set to 155 K.
Temperature set to 160 K.
Temperature set to 165 K.
Temperature set to 170 K.
Temperature set to 175 K.
Temperature set to 180 K.
Temperature set to 185 K.
Temperature set to 190 K.
Temperature set to 195 K.
Temperature set to 200 K.
Temperature set to 205 K.
Temperature set to 210 K.
Temperature set to 215 K.
Temperature set to 220 K.
Temperature set to 225 K.
1.2%	75000	74.99999999999406	-298195.27121149446	61282.330445811276	-236912.9407656832	219.17304128056955	436.71501073010984	0.6650702953374323	392	23:01
Temperature set to 230 K.
Temperature set to 235 K.
Temperature set to 240 K.
Temperature set to 245 K.
Temperature set to 250 K.
Temperature set to 255 K.
Temperature set to 260 K.
Temperature set to 265 K.
Temperature set to 270 K.
Temperature set to 275 K.
Temperature set to 280 K.
Temperature set to 285 K.
Temperature set to 290 K.
Temperature set to 295 K.
Adding a Montecarlo Barostat to the system
Running simulation in NPT ensemble for 25.0 ns
1.6%	100000	100.16200000011344	-245547.54090177268	105053.90253214823	-140493.63836962444	375.7197735279214	433.9189931725395	0.6693557685525735	396	22:47
Traceback (most recent call last):
  File "/home/gsk/anaconda3/envs/cosolvkit/bin/create_cosolvent_system", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/cli/create_cosolvent_system.py", line 163, in main
    run_simulation(
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/cosolvkit/simulation.py", line 158, in run_simulation
    simulation.step(simulation_steps) #25000000 = 100ns
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/simulation.py", line 212, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsk/anaconda3/envs/cosolvkit/lib/python3.11/site-packages/openmm/openmm.py", line 15287, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Particle coordinate is NaN. 


Also, is it possible to simulate protein-ligand complex in mixed solvent with cosolvkit? Any particular tutorial for that?

Best Regards, 
Gagan
